#!/bin/bash
sudo sed -i 's/^#MaxAuthTries\s.*/MaxAuthTries 600/' /etc/ssh/sshd_config
sed -i 's/^#MaxSessions\s.*/MaxSessions 1000/' /etc/ssh/sshd_config
sed -i 's/^#ClientAliveCountMax\s.*/ClientAliveCountMax 3000/' /etc/ssh/sshd_config
sudo systemctl restart ssh
